services:
  - type: web
    name: my-levelup-api
    env: node
    rootDir: backend
    buildCommand: npm install && npm run build && npx prisma generate
    startCommand: node dist/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_EXPIRES_IN
        value: 24h
      - key: OPENROUTER_MODEL
        value: meta-llama/llama-3.3-70b-instruct:free
      - key: DATABASE_URL
        generateValue: false
      - key: JWT_SECRET
        generateValue: false
      - key: OPENROUTER_API_KEY
        generateValue: false
      - key: FRONTEND_URL
        generateValue: false

  - type: web
    name: my-levelup
    env: static
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_URL
        generateValue: false
