export const IA_RULES = {
  MIN_CALORIES: 1200,
  MAX_CALORIES: 4500,
  MIN_REPS: 1,
  MAX_REPS: 50,
  MIN_SESSIONS_PER_WEEK: 1,
  MAX_SESSIONS_PER_WEEK: 7,
  POINTS_PER_SESSION: 10,
  STREAK_BONUS: 5,
}
